export const handleError = async ({ error, event }) => {
	return {
		message: 'Whoops!'
	};
};
